[package]
name = "biomc_pp"
description = "Python bindings"
edition.workspace = true
license.workspace = true
version.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
publish = true

[package.metadata.maturin]
bindings = "pyo3"

[dependencies]
biomc_pp_core = { path = "../core" }
numpy = "0.25.0"
pyo3 = { version = "0.25.1" }


[lib]
name = "biomc_pp"
path = "src/lib.rs"
crate-type = ["cdylib","rlib"]


[features]
embed = ["pyo3/auto-initialize"]