name: rust_test

on:
  push:
    branches:
      - main
      - test_ci
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libhdf5-dev

      - name: Cargo test
        run: |
          cargo test